version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - IMAGE_URI=public.ecr.aws/i0r7n1w5/yp-fulfillment:latest

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo Pushing the Docker image to ECR Public...
      - docker push $IMAGE_URI
      - echo $IMAGE_URI > imageDetail.txt

artifacts:
  files:
    - imageDetail.txt

